version: '3'
services:

  server:
    container_name: server
    build:
      context: ./services/server/
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    # env_file:
    #   - .env
    ports:
      - "8888:8888"
    volumes:
      - ./services/server:/server

  client:
    container_name: client
    build:
      context: ./services/client/
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    # env_file:
    #   - .env
    volumes:
      - ./services/client:/client
    depends_on:
      - server
    stdin_open: true
    tty: true






volumes:
  data: { }
